# Generated by Django 4.2.4 on 2023-09-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acceleration_x', models.FloatField()),
                ('acceleration_y', models.FloatField()),
                ('acceleration_z', models.FloatField()),
                ('gyroscope_x', models.FloatField()),
                ('gyroscope_y', models.FloatField()),
                ('gyroscope_z', models.FloatField()),
            ],
        ),
    ]
