# Generated by Django 4.2.4 on 2023-09-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_twinning_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='magnetometer_x',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='magnetometer_y',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='magnetometer_z',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
